server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: czyzlowie-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/czyzlowie-db}
    username: ${SPRING_DATASOURCE_USERNAME:czyzlowie-admin}
    password: ${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          jdbc.batch_size: 50
          order_inserts: true
          order_updates: true
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  ratelimiter:
    instances:
      default:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

weather:
  api:
    imgw-base-url: https://danepubliczne.imgw.pl/api
    open-meteo-base-url: https://api.open-meteo.com/v1
  sync:
    enabled: true
    synop-cron: "0 15 * * * *"
    meteo-cron: "0 */10 * * * *"
    hydro-cron: "0 */10 * * * *"
    batch-size: 50
    deduplication-window-hours: 48